### ISSUE TITLE
How to get the pre result in part_seg

### ISSUE THREAD

**Issue by lllmmmwww** [yanx27/Pointnet_Pointnet2_pytorch#103]
Hi!I have one question.How to get the forecast result of part_seg? This result contains all the input points and their label, not just the sampling points.Look forward to your reply!

**Comment by yanx27** [comment]
Hi @lllmmmwww , this protocol follows the that in official PointNet. Actually, we just give the class category of each object, but we want to predict its per-point's category.

**Comment by mypy98** [comment]
I have trained my own model now, but it is labeled in the test, but I need help on how to predict my unlabeled data. Have you finished?

**Comment by mypy98** [comment]
HI  @yanx27,  show3d_balls.py  can only display test data. but all of them are labeled. Can it have the function of prediction labels to display prediction results?.

**Comment by 7Julytree** [comment]
> HI @yanx27, show3d_balls.py can only display test data. but all of them are labeled. Can it have the function of prediction labels to display prediction results?.



> I have trained my own model now, but it is labeled in the test, but I need help on how to predict my unlabeled data. Have you finished?
Hello, I have the same problem as you. Have you solved it? Looking forward to your reply

**Comment by 7Julytree** [comment]
> I have trained my own model now, but it is labeled in the test, but I need help on how to predict my unlabeled data. Have you finished?

Hello, I have the same problem as you. Have you solved it? Looking forward to your reply

**Comment by kunaltilaganji** [comment]
Hello, I am trying to replicate the part_seg code.
But I am facing issues as the data is not being loaded

Here is the error:
Traceback (most recent call last):
  File "/Data3/yusha_kunal_data/Pointnet_Pointnet2_pytorch/train_partseg.py", line 301, in <module>
    main(args)
  File "/Data3/yusha_kunal_data/Pointnet_Pointnet2_pytorch/train_partseg.py", line 100, in main
    trainDataLoader = torch.utils.data.DataLoader(TRAIN_DATASET, batch_size=args.batch_size, shuffle=True, num_workers=10, drop_last=True)
  File "/home/student_kunal/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/student_kunal/.local/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

I intend to train my own dataset later so I need some help with this.
