### ISSUE TITLE
怎么标注点云分割的数据集啊？ 急死孩子了

### ISSUE THREAD

**Issue by lzh1998-jansen** [yanx27/Pointnet_Pointnet2_pytorch#129]
我做过图像的分割，换到点云，真的是无从下手啊，有没有大神，能指点一下，怎么标注数据集

**Comment by yqmy0814** [comment]
用CloudCompare就可以，上面那个剪刀是分割，+号是打标签，上手很快的

**Comment by lzh1998-lzh** [comment]
还有就是第一步，装虚拟环境的时候就会报错，我百度，改了一些东西，才能装上的，pointnet是死活装不上

**Comment by yqmy0814** [comment]
![2021-10-15 10-41-05 的屏幕截图](https://user-images.githubusercontent.com/55819722/137423916-a5413c90-dda2-465e-bf5a-c668f424ba9a.png)

**Comment by yqmy0814** [comment]
基本操作你百度一下，自己上手试试就会了

**Comment by lzh1998-lzh** [comment]
您好，我在标注自己的点云分割数据集了，请问接下来训练自己的数据集要修改哪些地方吗？，我的数据集仿照斯坦福的数据集，用前六列，但是我还有一部分点云数据集，是没有rgb信息的，请问这样的数据集可以训练吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanx27/Pointnet_Pointnet2_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanx27/Pointnet_Pointnet2_pytorch] 怎么标注点云分割的数据集啊？ 急死孩子了 (#129)





 
基本操作你百度一下，自己上手试试就会了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yqmy0814** [comment]
> 
> 您好，我在标注自己的点云分割数据集了，请问接下来训练自己的数据集要修改哪些地方吗？，我的数据集仿照斯坦福的数据集，用前六列，但是我还有一部分点云数据集，是没有rgb信息的，请问这样的数据集可以训练吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yanx27/Pointnet_Pointnet2_pytorch" ***@***.***&gt;; 发送时间:&nbsp;2021年10月15日(星期五) 上午10:44 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yanx27/Pointnet_Pointnet2_pytorch] 怎么标注点云分割的数据集啊？ 急死孩子了 (#129) 基本操作你百度一下，自己上手试试就会了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我这边只用到部件分割，场景分割没用到，斯坦福数据集的使用我就不太了解了

**Comment by bwlstart** [comment]
> 

你好，请问我想用部件分割部分分割自己的数据集，现在我只有已标注了的txt文件，现在的想法是要把数据集做成shapeNet的那个格式，我只有一个类和14个部件，请问shapeNet数据集中的那些编号像02691156这种数字是自己随便取的还是有什么特殊含义吗，还有文件中的train_test_split中的json文件怎么制作呢，谢谢

**Comment by bwlstart** [comment]
> > > 
> > 
> > 
> > 你好，请问我想用部件分割部分分割自己的数据集，现在我只有已标注了的txt文件，现在的想法是要把数据集做成shapeNet的那个格式，我只有一个类和14个部件，请问shapeNet数据集中的那些编号像02691156这种数字是自己随便取的还是有什么特殊含义吗，还有文件中的train_test_split中的json文件怎么制作呢，谢谢
> 
> 数字本身是没什么意义的，首先要改synsetoffset2category.txt，左边是类型名字，右边是你放txt的文件夹名字，三个json分别记录测试集、训练集和验证集的文件名，格式类似于["shape_data/《放txt的文件夹》/没后缀的文件名1"，"shape_data/《放txt的文件夹》/没后缀的文件名2"，……]，这个你打开这几个json照着填就是了。 程序里面也得改，不过具体改哪些我已经忘了，一时半会也找不全，你先试试吧

好的，我先试一下，非常感谢！

**Comment by bwlstart** [comment]
> > > 
> > 
> > 
> > 你好，请问我想用部件分割部分分割自己的数据集，现在我只有已标注了的txt文件，现在的想法是要把数据集做成shapeNet的那个格式，我只有一个类和14个部件，请问shapeNet数据集中的那些编号像02691156这种数字是自己随便取的还是有什么特殊含义吗，还有文件中的train_test_split中的json文件怎么制作呢，谢谢
> 
> 数字本身是没什么意义的，首先要改synsetoffset2category.txt，左边是类型名字，右边是你放txt的文件夹名字，三个json分别记录测试集、训练集和验证集的文件名，格式类似于["shape_data/《放txt的文件夹》/没后缀的文件名1"，"shape_data/《放txt的文件夹》/没后缀的文件名2"，……]，这个你打开这几个json照着填就是了。 程序里面也得改，不过具体改哪些我已经忘了，一时半会也找不全，你先试试吧

您好，我按照shapenet的数据集格式做了自己的数据集，修改了代码的部分，但是在执行训练的命令时报错`Namespace(batch_size=1, decay_rate=0.0001, epoch=500, gpu='0', learning_rate=0.001, log_dir='pointnet2_part_seg_msg', lr_decay=0.5, model='pointnet2_part_seg_msg', normal=True, npoint=2048, optimizer='Adam', step_size=20)
Traceback (most recent call last):
  File "train_partseg.py", line 302, in <module>
    main(args)
  File "train_partseg.py", line 100, in main
    TRAIN_DATASET = PartNormalDataset(root=root, npoints=args.npoint, split='trainval', normal_channel=args.normal)
  File "/home/bianwanlong/Tooth/Pointnet_Pointnet2_pytorch-tooth/data_utils/ShapeNetDataLoader.py", line 28, in __init__
    self.cat[ls[0]] = ls[1]
IndexError: list index out of range
` 我的数据集共1个类别，14个部件，每份数据大概是10万行左右，4列（xyz+label），请问这个问题的原因是数据点数太多的原因吗？

**Comment by yqmy0814** [comment]
> 

你把数据改成七列试试，中间三列法向量随便填充一下

**Comment by bwlstart** [comment]
> > 
> 
> 你把数据改成七列试试，中间三列法向量随便填充一下

您好，我已经将点云的法向量加上了，但是还是报跟上面同样的错误
PARAMETER ...
Namespace(batch_size=16, decay_rate=0.0001, epoch=251, gpu='0', learning_rate=0.001, log_dir='pointnet2_part_seg_msg', lr_decay=0.5, model='pointnet2_part_seg_msg', normal=True, npoint=2048, optimizer='Adam', step_size=20)
Traceback (most recent call last):
  File "train_partseg.py", line 302, in <module>
    main(args)
  File "train_partseg.py", line 100, in main
    TRAIN_DATASET = PartNormalDataset(root=root, npoints=args.npoint, split='trainval', normal_channel=args.normal)
  File "/home/bianwanlong/Tooth/Pointnet_Pointnet2_pytorch-tooth/data_utils/ShapeNetDataLoader.py", line 28, in __init__
    self.cat[ls[0]] = ls[1]
IndexError: list index out of range
请问还有别的错误的可能性吗？

**Comment by hongzhiqiang67** [comment]
@yqmy0814 Hello, I have made my own split dataset in XYZRGB format, but 8 columns are established when converted to npy format.
for i, data in tqdm(enumerate(trainDataLoader), total=len(trainDataLoader), smoothing=0.9):An error is reported here

**Comment by GUANHAO12** [comment]
> > > 
> > 
> > 
> > 你好，请问我想用部件分割部分分割自己的数据集，现在我只有已标注了的txt文件，现在的想法是要把数据集做成shapeNet的那个格式，我只有一个类和14个部件，请问shapeNet数据集中的那些编号像02691156这种数字是自己随便取的还是有什么特殊含义吗，还有文件中的train_test_split中的json文件怎么制作呢，谢谢
> 
> 数字本身是没什么意义的，首先要改synsetoffset2category.txt，左边是类型名字，右边是你放txt的文件夹名字，三个json分别记录测试集、训练集和验证集的文件名，格式类似于["shape_data/《放txt的文件夹》/没后缀的文件名1"，"shape_data/《放txt的文件夹》/没后缀的文件名2"，……]，这个你打开这几个json照着填就是了。 程序里面也得改，不过具体改哪些我已经忘了，一时半会也找不全，你先试试吧

您好，可以添加一下您微信吗？我正在做自己的数据集，跑部件分割模型

**Comment by 13717630148** [comment]
@bwlstart 请问没有rgb信息的自定义数据能用于训练么
