### ISSUE TITLE
Semantic segmentation tests its own dataset and reports errors

### ISSUE THREAD

**Issue by bukeyan4318** [yanx27/Pointnet_Pointnet2_pytorch#130]
Hi, thanks for your nice work.
When I tested semantic segmentation, I reported an error and couldn't understand it. I hope I can get your help. Thank you in advance.
_Traceback (most recent call last):
  File "test_semseg.py", line 202, in <module>
    main(args)
  File "test_semseg.py", line 118, in main
    scene_data, scene_label, scene_smpw, scene_point_index = TEST_DATASET_WHOLE_SCENE[batch_idx]
  File "/shiyanshi2/user/sunyijun/code/Pointnet2-own/data_utils/S3DISDataLoader.py", line 164, in __getitem__
    data_room = data_room.reshape((-1, self.block_points, data_room.shape[1]))
IndexError: tuple index out of range_

**Comment by jiayaozi** [comment]
hello,same error,have you solved that?

**Comment by foysalahmed10** [comment]
@jiayaozi @bukeyan4318 @wyz5008 have you solved this problem?

**Comment by morankim** [comment]
Hi, I solved this by adding a 7th element in data array. 
maybe your dataset is composed of (x, y, z, r, g, b). transform this -> (x, y, z, r, g, b, label)
where 0<= label <= num_class. but I just initialized lebel = 0 for all point cloud. and the result was fine. 
anyway, you need to give initial label index which can be set as random number btw 0~ num_class.

**Comment by jianuo1128** [comment]
> Hi, I solved this by adding a 7th element in data array. maybe your dataset is composed of (x, y, z, r, g, b). transform this -> (x, y, z, r, g, b, label) where 0<= label <= num_class. but I just initialized lebel = 0 for all point cloud. and the result was fine. anyway, you need to give initial label index which can be set as random number btw 0~ num_class.
请问你说的解决办法是指在构建自己的数据集的时候在(x,y,z,r,g,b)这后面加上第七列label吗，这个是针对所有的数据，还是单指用于测试的数据

**Comment by jianuo1128** [comment]
> Hi, I solved this by adding a 7th element in data array. maybe your dataset is composed of (x, y, z, r, g, b). transform this -> (x, y, z, r, g, b, label) where 0<= label <= num_class. but I just initialized lebel = 0 for all point cloud. and the result was fine. anyway, you need to give initial label index which can be set as random number btw 0~ num_class.
@morankim 
my question:
Does the solution you mean by adding a seventh column of labels after (x,y,z,r,g,b) when building your own dataset, is this for all the data, or just for the data used for testing?

**Comment by jianuo1128** [comment]
> 嗨，我通过在数据数组中添加第 7 个元素解决了这个问题。也许您的数据集由 （x、y、z、r、g、b） 组成。转换这个 -> （x， y， z， r， g， b， label），其中 0<= 标签 <= num_class。 但我刚刚初始化了所有点云的 lebel = 0。结果很好。无论如何，您需要给出初始标签索引，该索引可以设置为随机数顺便说一句 0~ num_class。

使用collect_indoor3d_data.py将txt数据转换为.npy格式后，查看npy文件的shape，发现就是7维的，包括(x,y,z,r,g,b,label)，所以输入进test的是7维的

**Comment by jianuo1128** [comment]
> 嗨，感谢您的出色工作。当我测试语义分割时，我报告了一个错误并且无法理解它。我希望我能得到你的帮助。先谢谢你。 _回溯（最近一次调用最后一次）：文件“test_semseg.py”，第 202 行，在 main（args） 文件“test_semseg.py”，第 118 行，在主scene_data中，scene_label，scene_smpw，scene_point_index = TEST_DATASET_WHOLE_SCENE[batch_idx] 文件“/shiyanshi2/user/sunyijun/code/Pointnet2-own/data_utils/S3DISDataLoader.py”，第 164 行，在 **getitem** data_room = data_room.reshape（（-1， self.block_points， data_room.shape[1]）） IndexError：元组索引超出范围_

你好，问题解决了吗
