### ISSUE TITLE
Semantic Segmentation ran out of input

### ISSUE THREAD

**Issue by devpatric** [yanx27/Pointnet_Pointnet2_pytorch#48]
Hi, 
running train_semseg.py as instructed in the readme gives me following errors

python train_semseg.py --model pointnet2_sem_seg --test_area 5 --log_dir pointnet2_sem_seg
PARAMETER ...
Namespace(batch_size=16, decay_rate=0.0001, epoch=128, gpu='0', learning_rate=0.001, log_dir='pointnet2_sem_seg', lr_decay=0.7, model='pointnet2_sem_seg', npoint=4096, optimizer='Adam', step_size=10, test_area=5)
start loading training data ...
[1.124833  1.1816078 1.        2.2412012 2.340336  2.343587  1.7070498
 2.0335796 1.8852289 3.8252103 1.7948895 2.7857335 1.3452303]
Totally 47623 samples in train set.
start loading test data ...
[1.1381457 1.2059734 1.        9.996554  2.5299199 2.0086675 2.1162353
 1.9657742 2.4815738 4.727607  1.4018297 2.8840992 1.4809785]
Totally 18923 samples in test set.
The number of training data is: 47623
The number of test data is: 18923
No existing model, starting training from scratch...
**** Epoch 1 (1/128) ****
Learning rate:0.001000
BN momentum updated to: 0.100000
Traceback (most recent call last):
  File "train_semseg.py", line 274, in <module>
    main(args)
  File "train_semseg.py", line 168, in main
    for i, data in tqdm(enumerate(trainDataLoader), total=len(trainDataLoader), smoothing=0.9):
  File "C:\Users\API\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\API\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "C:\Users\API\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\API\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\API\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\API\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\API\AppData\Local\Programs\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\API\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\API\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

any ideas ? thank you

**Comment by devpatric** [comment]
fixed it, using linux instead of windows 10

**Comment by Jangliu** [comment]
In windows10. You can change num_workers to 0 in train_semseg.py

**Comment by Wadetech** [comment]
1

**Comment by Wadetech** [comment]
1

**Comment by lapllibary** [comment]
Thanks
